### ISSUE TITLE
Replace in visual mode not working as expected

### ISSUE THREAD

**Issue by piersolenski** [VonHeikemen/searchbox.nvim#2]
Am I correct in assuming this should prepopulate the search box with the selected text, then allow you to replace it?

> Replace an exact match in the selected text. (Needs to be mapped in visual mode)
> 
> ```vim
> <Esc><cmd>lua require("searchbox").replace({exact = true, visual_mode = true})<CR>
> ```

Currently, that mapping just launches the normal search and replace box from visual mode for me... I was hoping for something along the lines of the following mapping if possible!

```lua
map("v", "<leader>s", 'y<Esc>:%s/<C-R>"//g<Left><Left>', { noremap = true })
```

Awesome work so far!

**Comment by VonHeikemen** [comment]
No, the visual mode just limits the search to the selected text, like `:'<,'>s:/this/that/g`.

I believe what you're looking for is this:

```lua
<Esc><cmd>lua require('searchbox').replace({default_value = vim.fn.getreg('/')})<CR>
```

Due to limitations on the input, It can't handle newline well or even the escape sequence `\n`. So whatever is on register `/` must be one line.

To get word under the cursor you do this.

```lua
<cmd>lua require('searchbox').replace({default_value = vim.fn.expand('<cword>')})<CR>
```

**Comment by piersolenski** [comment]
Ahh awesome! Thank you!
