### ISSUE TITLE
Go to next input does not move cursor

### ISSUE THREAD

**Issue by ASKabalan** [VonHeikemen/searchbox.nvim#33]
Hello,

Thank you very much for SearchBox :)

I was wondering if there is a way to keep the cursor at the search we get to after `ctrl + l`.
If I submit the search or hit `Esc` I go back to the first search hit

Thank you

**Comment by VonHeikemen** [comment]
I have implemented this behavior in [510144c](https://github.com/VonHeikemen/searchbox.nvim/commit/510144c1a97bf3014ea46b59ba7d1cd98637ebd5), you can update the plugin and test it.

**Comment by ASKabalan** [comment]
Perfect, works very well

**Comment by Myphz** [comment]
This happens again if using this plugin in combination to Lazy distro.
Search works fine, but after pressing CTRL+L and then pressing enter/esc, the cursor is brought back to the first result.

This is caused by Folke's snacks animate plugin. By disabling it, the plugin works correctly (https://www.lazyvim.org/news)
