### ISSUE TITLE
Is it possible to switch between Search & replace dinamically?

### ISSUE THREAD

**Issue by uwla** [VonHeikemen/searchbox.nvim#34]
Is it possible to toggle between the search  box  (SearchBoxIncSearch)  and  the
replace (SearchBoxReplace) without leaving the box? Like in VSCode  and  popular
IDEs, you can press `<C-f>` to start a search, jump between the matches, and  if
you press `<C-r>` it enters replace mode.

A possible solution that came to mind was:

1. Start search via some keybinding
2. Set a custom map local to the buffer of the floating window:
    ```vim
    inoremap <buffer> <C-r> <Esc>Vy<cmd>SearchBoxReplace -- <C-r>0<CR><CR>
    ```
3. Proceds to replace

That mapping will exit insert mode, visual select the whole line and yank it,
then run a cmd inserting the yanked text.

But, the question is, how to create such custom mapping local only to the buffer
of the floating searchbox window?

Thanks in advance.

**Comment by VonHeikemen** [comment]
You have to create the keymap after the floating input is in the screen.

You can try this:

```lua
require('searchbox').setup({
  hooks = {
    after_mount = function(input)
      vim.keymap.set(
        'i',
        '<C-r>',
        '<Esc>^y$<Plug>(searchbox-close):SearchBoxReplace -- <C-r>0<cr>',
        {buffer = input.bufnr}
      )
    end,
  }
})
```

It still a little bit awkward because you can't skip the first input of the replace command.

I probably need to add another command like `SearchBoxReplaceLast` so you can jump directly to the replace step using the last search.
